CREATE TABLE IF NOT EXISTS organizational_units (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  unit_type VARCHAR(50) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO organizational_units (code, name, unit_type)
VALUES
('P&P', 'POLICY AND PLANS BRANCH', 'HQ_BRANCH'),
('TRG', 'TRAINING BRANCH', 'HQ_BRANCH'),
('OPS', 'OPERATIONS BRANCH', 'HQ_BRANCH'),
('AINT', 'AIR INTELLIGENCE BRANCH', 'HQ_BRANCH'),
('AENG', 'AIRCRAFT ENGINEERING BRANCH', 'HQ_BRANCH'),
('CIS', 'COMMUNICATION AND INFORMATION SYSTEMS BRANCH', 'HQ_BRANCH'),
('LOG', 'LOGISTICS BRANCH', 'HQ_BRANCH'),
('ADMIN', 'ADMINISTRATION BRANCH', 'HQ_BRANCH'),
('AS', 'AIR SECRETARY BRANCH', 'HQ_BRANCH'),
('A&B', 'ACCOUNTS AND BUDGET BRANCH', 'HQ_BRANCH'),
('MED', 'MEDICAL SERVICES BRANCH', 'HQ_BRANCH'),
('T&I', 'TRANSFORMATION AND INNOVATION BRANCH', 'HQ_BRANCH'),
('CMR', 'CIVIL MILITARY RELATION BRANCH', 'HQ_BRANCH'),

('PIMT', 'PIMT', 'DIRECT_TO_CAS_OFFICE'),
('BOSE', 'BOSE', 'DIRECT_TO_CAS_OFFICE'),
('DAP', 'DIRECTORATE OF AIR POLICE', 'DIRECT_TO_CAS_OFFICE'),
('DPROC', 'DIRECTORATE OF PROCUREMENT', 'DIRECT_TO_CAS_OFFICE'),
('DPRINFO', 'DIRECTORATE OF PUBLIC RELATIONS & INFO', 'DIRECT_TO_CAS_OFFICE')
ON CONFLICT (code) DO UPDATE
SET
  name = EXCLUDED.name,
  unit_type = EXCLUDED.unit_type,
  is_active = TRUE,
  updated_at = NOW();